-- 자동 생성 파일 — 직접 수정하지 말 것.
-- 생성: 로컬 Postgres(Hibernate ddl-auto=update 로 만든 실제 스키마)에서
--       pg_dump --schema-only 로 추출.
-- 단일 진실 공급원은 backend/src/main/java/.../domain/**/*.java 의 JPA
-- 엔티티다 — 이 파일은 그 결과물을 보여주기 위한 스냅샷이며, 컬럼을 여기서
-- 고쳐도 애플리케이션 동작에는 반영되지 않는다.
--
-- 제약 이름 표기 안내: Hibernate 가 자동 생성하는 제약/인덱스 이름 중 일부는
-- 해시 형태(예: ukaye4nalvpsbxpjq0vt2ulaiqi, fk191omxcw1b6p8hckvsjrng68m)라
-- 이 파일에서만 사람이 읽을 수 있는 이름(uk_*, fk_*)으로 바꿔 표기했다.
-- 실제 DB의 제약 이름은 다르며, 재실행 가능한 DDL로 쓰려는 목적이 아니다.
--
-- ┌──────────────────────────────────────────────────────────────────────┐
-- │  테이블 구성 & 멀티테넌시 설계                                        │
-- │                                                                      │
-- │  TENANTS ──── 테넌트(게임사) 마스터. CODE 가 전역 유일(UNIQUE) —      │
-- │               AI 서버가 Elasticsearch 인덱스를 items-{code} 로        │
-- │               고르는 값과 동일하다(index-per-tenant, ai/scripts/      │
-- │               seed_items.py --tenant 로 검증).                       │
-- │  USERS ────── 회원. (tenant_id, username) 복합 UNIQUE — 아이디는      │
-- │               테넌트 안에서만 유일하면 된다(전역 유일 아님).          │
-- │  ITEMS ────── 거래 대상. current_bid_price/current_bidder_id 는       │
-- │               sale_type=AUCTION 일 때만 채워진다. version 컬럼은      │
-- │               Redis 분산 락과 별개인 낙관적 락(최후 방어선).          │
-- │  TRADES ───── 구매/입찰 기록.                                        │
-- │  NOTIFICATIONS ─ 거래 알림. (recipient_id, trade_id) 복합 UNIQUE —    │
-- │               RabbitMQ 컨슈머의 중복 처리 방지용 사전 체크가 기대는   │
-- │               제약(ADR-0048 — 예외 catch 로는 못 막아서 이 제약 +     │
-- │               재시도로 대체).                                        │
-- │                                                                      │
-- │  다섯 테이블 전부 tenant_id 컬럼 + idx_*_tenant_id 인덱스를 갖는다 —  │
-- │  이 저장소의 테넌트 격리는 "스키마 레벨 강제"가 아니라 "모든 조회에   │
-- │  tenant_id 필터를 붙이는" 애플리케이션 레벨 규칙이며, 그 전수 여부는  │
-- │  ADR-0057 감사 대상이다(강제 아님 — 감사로 검증하는 방식).           │
-- └──────────────────────────────────────────────────────────────────────┘


--==============================================================================
-- 1. TENANTS — 테넌트(게임사) 마스터
--==============================================================================
CREATE TABLE tenants (
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at  timestamp(6) without time zone,
    updated_at  timestamp(6) without time zone,
    code        character varying(50)  NOT NULL,
    name        character varying(100) NOT NULL,
    --
    CONSTRAINT tenants_pkey        PRIMARY KEY (id),
    CONSTRAINT uk_tenants_code     UNIQUE      (code)
);


--==============================================================================
-- 2. USERS — 회원
--==============================================================================
CREATE TABLE users (
    id             bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at     timestamp(6) without time zone,
    updated_at     timestamp(6) without time zone,
    email          character varying(100) NOT NULL,
    password_hash  character varying(255) NOT NULL,
    role           character varying(20)  NOT NULL,
    username       character varying(50)  NOT NULL,
    tenant_id      bigint NOT NULL,
    --
    CONSTRAINT users_pkey             PRIMARY KEY (id),
    CONSTRAINT uk_users_tenant_username UNIQUE    (tenant_id, username),
    CONSTRAINT users_role_check       CHECK       (role IN ('USER', 'ADMIN')),
    CONSTRAINT fk_users_tenant        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
);

CREATE INDEX idx_users_tenant_id ON users (tenant_id);


--==============================================================================
-- 3. ITEMS — 거래 대상 (아이템/계정/재화 등)
--==============================================================================
CREATE TABLE items (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at         timestamp(6) without time zone,
    updated_at         timestamp(6) without time zone,
    current_bid_price  numeric(19,2),
    description        text,
    name               character varying(200) NOT NULL,
    price              numeric(19,2)          NOT NULL,
    sale_type          character varying(20)  NOT NULL,
    status             character varying(20)  NOT NULL,
    stock              integer                NOT NULL,
    version            bigint                 NOT NULL,  -- 낙관적 락 (@Version)
    current_bidder_id  bigint,
    seller_id          bigint NOT NULL,
    tenant_id          bigint NOT NULL,
    --
    CONSTRAINT items_pkey           PRIMARY KEY (id),
    CONSTRAINT items_sale_type_check CHECK      (sale_type IN ('FIXED_PRICE', 'AUCTION')),
    CONSTRAINT items_status_check    CHECK      (status IN ('ON_SALE', 'SOLD_OUT', 'CLOSED')),
    CONSTRAINT fk_items_tenant         FOREIGN KEY (tenant_id)         REFERENCES tenants (id),
    CONSTRAINT fk_items_seller         FOREIGN KEY (seller_id)         REFERENCES users   (id),
    CONSTRAINT fk_items_current_bidder FOREIGN KEY (current_bidder_id) REFERENCES users   (id)
);

CREATE INDEX idx_items_tenant_id ON items (tenant_id);


--==============================================================================
-- 4. TRADES — 구매/입찰 기록
--==============================================================================
CREATE TABLE trades (
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at  timestamp(6) without time zone,
    updated_at  timestamp(6) without time zone,
    price       numeric(19,2)          NOT NULL,
    quantity    integer                NOT NULL,
    status      character varying(20)  NOT NULL,
    trade_type  character varying(20)  NOT NULL,
    buyer_id    bigint NOT NULL,
    item_id     bigint NOT NULL,
    seller_id   bigint NOT NULL,
    tenant_id   bigint NOT NULL,
    --
    CONSTRAINT trades_pkey             PRIMARY KEY (id),
    CONSTRAINT trades_status_check     CHECK       (status IN ('COMPLETED', 'ACTIVE', 'OUTBID', 'CANCELLED')),
    CONSTRAINT trades_trade_type_check CHECK       (trade_type IN ('PURCHASE', 'BID')),
    CONSTRAINT fk_trades_tenant  FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_trades_item    FOREIGN KEY (item_id)   REFERENCES items   (id),
    CONSTRAINT fk_trades_buyer   FOREIGN KEY (buyer_id)  REFERENCES users   (id),
    CONSTRAINT fk_trades_seller  FOREIGN KEY (seller_id) REFERENCES users   (id)
);

CREATE INDEX idx_trades_tenant_id ON trades (tenant_id);


--==============================================================================
-- 5. NOTIFICATIONS — 거래 알림
--==============================================================================
CREATE TABLE notifications (
    id            bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at    timestamp(6) without time zone,
    updated_at    timestamp(6) without time zone,
    message       character varying(200) NOT NULL,
    read          boolean                NOT NULL,
    trade_id      bigint NOT NULL,  -- FK 아님(값만) — 알림은 거래 수명주기에 묶이지 않는다
    type          character varying(20)  NOT NULL,
    recipient_id  bigint NOT NULL,
    tenant_id     bigint NOT NULL,
    --
    CONSTRAINT notifications_pkey      PRIMARY KEY (id),
    CONSTRAINT uk_notifications_recipient_trade UNIQUE (recipient_id, trade_id),
    CONSTRAINT notifications_type_check CHECK (type IN (
                                        'PURCHASE_COMPLETED',
                                        'ITEM_SOLD',
                                        'BID_PLACED',
                                        'OUTBID'
                                    )),
    CONSTRAINT fk_notifications_tenant    FOREIGN KEY (tenant_id)    REFERENCES tenants (id),
    CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_id) REFERENCES users   (id)
);

CREATE INDEX idx_notifications_tenant_id  ON notifications (tenant_id);
CREATE INDEX idx_notifications_recipient  ON notifications (recipient_id, id);


--------------------------------------------------------------------------------
-- 재생성 방법
--   1) docker compose up -d postgres
--   2) ./gradlew bootRun  (Hibernate ddl-auto=update 가 엔티티에서 스키마 생성)
--   3) docker exec gimp-postgres pg_dump -U gimp -d gimp --schema-only \
--        --no-owner --no-privileges
--------------------------------------------------------------------------------
